### ISSUE TITLE
Make Content Type Optional for File Uploads

### ISSUE THREAD

**Issue by tmciver** [AtomGraph/LinkedDataHub#110]
The script [create-file.sh](https://github.com/AtomGraph/LinkedDataHub/blob/3fa6726ac381603700cd6deba89ba0542cb34a58/scripts/imports/create-file.sh) expects the file's content type to be provided by the caller.  It would be convenient to make the content type optional and be automatically determined when not provided.  This would also make it less likely that the caller-provided content type would be inconsistent with the actual content type of the file.

**Comment by namedgraph** [comment]
Thanks @tmciver, this makes sense! I'll try it out ASAP.

**Comment by namedgraph** [comment]
Hi @tmciver. I didn't want to fix the conflicts in #111 but I incorporated your changes into the `develop` branch. Our tests pass, so that's OK from me.
Can you see if they work for you? `develop` also comes with an improved graph layout ;) If they do, we can close this.
Thanks for the contribution!
