### ISSUE TITLE
/admin gives 500 error: Could not read XML document from URI

### ISSUE THREAD

**Issue by djradon** [AtomGraph/LinkedDataHub#191]
I can access https://localhost:4443/ fine, but when I go to https://localhost:4443/admin/ I get this:

linkeddatahub-1     | 22:03:31,395 [http-nio-7070-exec-7]  WARN DataManagerImpl:160 - Could not read XML document from URI: https://localhost:4443/static/com/atomgraph/linkeddatahub/xsl/bootstrap/2.3.2/imports/dct.xsl
linkeddatahub-1     | Error on line 9 column 41 of layout.xsl:
linkeddatahub-1     |   XTSE0165  java.io.IOException: XML document could not be successfully loaded over HTTP.
linkeddatahub-1     |   Status code: 429. Caused by javax.xml.transform.TransformerException: java.io.IOException:
linkeddatahub-1     |   XML document could not be successfully loaded over HTTP. Status code: 429. Caused by
linkeddatahub-1     |   java.io.IOException: XML document could not be successfully loaded over HTTP. Status code: 429
linkeddatahub-1     | 22:03:31,395 [http-nio-7070-exec-7] ERROR XsltExecutableFilter:92 - XSLT transformer not configured property

I can retrieve https://localhost:4443/static/com/atomgraph/linkeddatahub/xsl/bootstrap/2.3.2/imports/dct.xsl no problem, and it looks like valid xml.

FYI, I'm running LDH from WSL2 (ubuntu 22.04). browser is Chrome

**Comment by namedgraph** [comment]
Hi. `429 Too Many Requests` is caused by nginx's request limiting.

Sometimes just refreshing the page works :) Once the stylesheets are loaded into memory they are not requested anymore.

If that doesn't work, you can try increasing the `rate` on `static_files` [here](https://github.com/AtomGraph/LinkedDataHub/blob/master/platform/nginx.conf.template#L13) and then do a `docker-compose up --force-recreate`.

**Comment by djradon** [comment]
Thanks, increasing the rate worked!
